### ISSUE TITLE
if it is specifically made for Yii2, why use singletons?

### ISSUE THREAD

**Issue by mikk150** [alexeevdv/yii2-zerobounce-client#4]
if it is specifically made for Yii2, why use singletons?

**Comment by alexeevdv** [comment]
There are no singletons in this repo.
If you talking about configuration then it is up to you how to use it. You can set it up as component if you like.

This is what Yii2 docs saying about this:

https://www.yiiframework.com/doc/guide/2.0/en/concept-di-container
 
>Another step on configuration optimization is to register some dependencies as singletons. A dependency registered via set() will be instantiated each time it is needed. Some classes do not change the state during runtime, therefore they may be registered as singletons in order to increase the application performance.

>A good example could be app\storage\FileStorage class, that executes some operations on file system with a simple API (e.g. $fs->read(), $fs->write()). These operations do not change the internal class state, so we can create its instance once and use it multiple times.

Also this way you dont depend on component name. If `Instance::ensure` is used to ensure ClientInterface then you can skip component configuration and set client definition right in container. Because what you actually need in your code is some object that implements interface.

Also with such configuration you can use auto wiring. Which is impossible in case of components.

```php
class A extends BaseObject
{
    public function __constuct(ClientInterface $client, $config = [])
    {
         //...
    }
}

// ClientInterface will be autowired here
$a = Instance::ensure(A::class);
```
There are more pros than cons for using container configuration instead of components. But from my point of view it is more suitable for single instance components such as api clients, database, etc
